QLKS_H2O/Models/TRANGTHAI_PHONG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TRANGTHAI_PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANGTHAI_PHONG()
        {
            this.PHONGs = new HashSet<PHONG>();
        }

        [DisplayName("Mã trạng thái")]
        public string MA_TRANGTHAI { get; set; }
        [DisplayName("Tên trạng thái")]
        public string TEN_TRANGTHAI { get; set; }
        [DisplayName("Mã màu")]
        public string MAMAU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}

QLKS_H2O/Models/VATTU.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class VATTU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VATTU()
        {
            this.VATTU_LOAIPHONG = new HashSet<VATTU_LOAIPHONG>();
        }

        [DisplayName("Mã vật tư")]
        [Required(ErrorMessage = "Chưa nhập mã vật tư")]
        public string MA_VATTU { get; set; }
        [DisplayName("Tên vật tư")]
        [Required(ErrorMessage = "Chưa nhập tên vật tư")]
        public string TEN_VATTU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VATTU_LOAIPHONG> VATTU_LOAIPHONG { get; set; }
    }
}

QLKS_H2O/Areas/Admin/Controllers/VatTuController.cs
using QLKS_H2O.Areas.Admin.Models;
using QLKS_H2O.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QLKS_H2O.Areas.Admin.Controllers
{
    public class VatTuController : BaseController
    {
        private QLKS_H2OEntities db = new QLKS_H2OEntities();

        // GET: VatTu
        public ActionResult Index(string maVT = "", string tenVT = "")
        {
            ViewBag.tag = "vattu";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            ViewBag.maVT = maVT;
            ViewBag.tenVT = tenVT;
            return View(db.VATTUs.Where(vt => (vt.MA_VATTU == maVT || maVT == "") && (vt.TEN_VATTU.Contains(tenVT) || tenVT == "")).ToList());
        }

        // GET: VatTu/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VATTU vATTU = db.VATTUs.Find(id);
            if (vATTU == null)
            {
                return HttpNotFound();
            }
            ViewBag.tag = "vattu";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(vATTU);
        }

        // GET: VatTu/Create
        public ActionResult Create()
        {
            ViewBag.tag = "vattu";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View();
        }

        // POST: VatTu/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MA_VATTU,TEN_VATTU")] VATTU vATTU)
        {
            if (ModelState.IsValid)
            {
                int count = db.VATTUs.Where(dv => dv.MA_VATTU == vATTU.MA_VATTU).Count();
                if (count == 0)
                {
                    db.VATTUs.Add(vATTU);

                    db.LOAIPHONGs.ToList().ForEach(lp =>
                    {
                        db.VATTU_LOAIPHONG.Add(new VATTU_LOAIPHONG()
                        {
                            MA_LOAIPHONG = lp.MA_LOAIPHONG,
                            MA_VATTU = vATTU.MA_VATTU,
                            SOLUONG = 0
                        });
                    });

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Vật tư đã tồn tại");
                }
            }
            ViewBag.tag = "vattu";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(vATTU);
        }

        // GET: VatTu/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VATTU vATTU = db.VATTUs.Find(id);
            if (vATTU == null)
            {
                return HttpNotFound();
            }
            ViewBag.tag = "vattu";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(vATTU);
        }

        // POST: VatTu/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MA_VATTU,TEN_VATTU")] VATTU vATTU)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vATTU).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.tag = "vattu";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(vATTU);
        }

        // GET: VatTu/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VATTU vATTU = db.VATTUs.Find(id);
            if (vATTU == null)
            {
                return HttpNotFound();
            }
            ViewBag.tag = "vattu";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(vATTU);
        }

        // POST: VatTu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            VATTU vATTU = db.VATTUs.Find(id);
            db.VATTUs.Remove(vATTU);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ThongKeVatTu(string loaiPhong = "abcxyz")
        {
            var thongKe = db.VATTU_LOAIPHONG.Where(ct => ct.MA_LOAIPHONG == loaiPhong).ToList();

            ViewBag.loaiPhong = new SelectList(db.LOAIPHONGs, "MA_LOAIPHONG", "TEN_LOAIPHONG", loaiPhong);

            ViewBag.tag = "thongke";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(thongKe);
        }

        public ActionResult EditChiTiet(string lp, string vt)
        {
            if (lp == null || vt == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var chiTiets = db.VATTU_LOAIPHONG.Where(ct => ct.MA_LOAIPHONG == lp && ct.MA_VATTU == vt);
            if (chiTiets.Count() <= 0)
            {
                return HttpNotFound();
            }
            ViewBag.tag = "thongke";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(chiTiets.First());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditChiTiet([Bind(Include = "MA_VATTU,MA_LOAIPHONG,SOLUONG")] VATTU_LOAIPHONG ct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ThongKeVatTu", new { loaiPhong = ct.MA_LOAIPHONG });
            }

            return View(ct);
        }

        public ActionResult TrangThaiPhong(string maP = "")
        {
            ViewBag.tag = "trangthai";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(db.PHONGs.Where(p => p.MA_PHONG == maP || maP == "").ToList());
        }

        public ActionResult CapNhatTrangThaiPhong(string maP, string maTT)
        {
            ViewBag.maP = maP;
            ViewBag.maTT = new SelectList(db.TRANGTHAI_PHONG, "MA_TRANGTHAI", "TEN_TRANGTHAI", maTT);
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            ViewBag.tag = "trangthai";
            return View();
        }

        [HttpPost]
        public ActionResult CapNhatTrangThaiPhong()
        {
            string maP = Request["maP"];
            string maTT = Request["maTT"];

            db.PHONGs.Find(maP).MA_TRANGTHAI = maTT;
            db.SaveChanges();

            return RedirectToAction("TrangThaiPhong");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKS_H2O/Areas/Admin/Views/VatTu/CapNhatTrangThaiPhong.cshtml
@{
    ViewBag.Title = "Cập nhật trạng thái phòng";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
}

<h4 class="text-center">Cập nhật trạng thái phòng</h4>
<div>
    @using (Html.BeginForm("CapNhatTrangThaiPhong", "VatTu", FormMethod.Post))
    {
        <table align="center" class="table1">
            <tr>
                <td>
                    <div>Phòng</div>
                </td>
                <td>
                    <input type="text" name="maP" value="@ViewBag.maP" class="form-control" readonly />
                </td>

            </tr>
            <tr>
                <td>Trạng thái phòng</td>
                <td>
                    @Html.DropDownList("maTT", null, new { @class="form-control"})
                </td>

            </tr>
            <tr>
                <td></td>
                <td>
                    <button type="submit" class="btn btn-sm btn-primary">Cập nhật</button>

                </td>
            </tr>
        </table>
    }
</div>

<div>
    <a href="javascript: history.go(-1)">Quay lại</a>
</div>

QLKS_H2O/Areas/Admin/Views/VatTu/Create.cshtml
@model QLKS_H2O.Models.VATTU
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
}

<h2>Thêm vật tư</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MA_VATTU, "Mã vật tư", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MA_VATTU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MA_VATTU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TEN_VATTU, "Tên vật tư", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEN_VATTU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEN_VATTU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-sm btn-success" /> |
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </div>
}

QLKS_H2O/Areas/Admin/Views/VatTu/Delete.cshtml
@model QLKS_H2O.Models.VATTU
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
}

<h3>Bạn có chắc muốn xóa vật tư này khỏi danh sách?</h3>
<div>
    <hr />
    <table class="table table-bordered table-striped text-center">
        <tr>
            <th>Mã vật tư</th>
            <th>Tên vật tư</th>
        </tr>

        <tr>
            <td>@Html.DisplayFor(model => model.MA_VATTU)</td>
            <td>@Html.DisplayFor(model => model.TEN_VATTU)</td>
        </tr>

    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-success" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

QLKS_H2O/Areas/Admin/Views/VatTu/Details.cshtml
@model QLKS_H2O.Models.VATTU

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
}

<h2>Thông tin vật tư</h2>

<div>
    <hr />
    <table class="table table-bordered table-striped text-center">
        <tr>
            <th>Mã vật tư</th>
            <th>Tên vật tư</th>
        </tr>

        <tr>
            <td>@Html.DisplayFor(model => model.MA_VATTU)</td>
            <td>@Html.DisplayFor(model => model.TEN_VATTU)</td>
        </tr>

    </table>
</div>
<p>
    @*@Html.ActionLink("Sửa", "Edit", new { id = Model.MA_VATTU}) |*@
    @Html.ActionLink("Quay lại", "Index")
</p>

QLKS_H2O/Areas/Admin/Views/VatTu/Edit.cshtml
@model QLKS_H2O.Models.VATTU
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
}

<h2>Sửa thông tin vật tư</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MA_VATTU)

        <div class="form-group">
            @Html.LabelFor(model => model.MA_VATTU, "Mã vật tư", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MA_VATTU, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MA_VATTU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TEN_VATTU, "Tên vật tư", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEN_VATTU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEN_VATTU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" /> |
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </div>
}

QLKS_H2O/Areas/Admin/Views/VatTu/EditChiTiet.cshtml
@model QLKS_H2O.Models.VATTU_LOAIPHONG
@{
    ViewBag.Title = "EditChiTiet";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal w-50 ">
        <h4>THÔNG TIN VẬT TƯ TRONG LOẠI PHÒNG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MA_VATTU)

        @Html.HiddenFor(model => model.MA_LOAIPHONG)

        <div class="form-group d-flex align-items-center">
            @Html.LabelFor(model => model.LOAIPHONG.TEN_LOAIPHONG, "Tên loại phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LOAIPHONG.TEN_LOAIPHONG, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.LOAIPHONG.TEN_LOAIPHONG, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group d-flex align-items-center">
            @Html.LabelFor(model => model.VATTU.TEN_VATTU, "Tên vật tư", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VATTU.TEN_VATTU, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.VATTU.TEN_VATTU, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group d-flex align-items-center">
            @Html.LabelFor(model => model.SOLUONG, "Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SOLUONG, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
                @Html.ValidationMessageFor(model => model.SOLUONG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 mt-4">
                <input type="submit" value="Cập nhật" class="btn btn-success" /> |
                @Html.ActionLink("Quay lại", "ThongKeVatTu")
            </div>
        </div>
    </div>
}

QLKS_H2O/Areas/Admin/Views/VatTu/Index.cshtml
@model IEnumerable<QLKS_H2O.Models.VATTU>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, rowsPerPage: 5);
}

<h4>DANH SÁCH VẬT TƯ</h4>

<p>
    @Html.ActionLink("Thêm vật tư", "Create")
</p>

<div>
    @using (Html.BeginForm("Index", "VatTu", FormMethod.Get))
    {
        <table align="center" class="table1">
            <tr>
                <td>
                    <div> Mã vật tư</div>
                </td>
                <td>
                    <input type="text" name="maVT" value="@ViewBag.maVT" class="form-control" />
                </td>

            </tr>
            <tr>
                <td>Tên vật tư</td>
                <td>
                    <input type="text" name="tenVT" value="@ViewBag.tenVT" class="form-control" />
                </td>

            </tr>
            <tr>
                <td></td>
                <td>
                    <button type="submit" class="btn btn-sm btn-primary">Tìm kiếm</button>
                    <a href="/Admin/VatTu/Index" role="button" class="btn btn-sm btn-primary">Nhập mới</a>

                </td>
            </tr>
        </table>
    }
</div>

@if(Model.Count() > 0)
{
<div id="gridContent">
    @ViewBag.TB
    @grid.GetHtml(
        tableStyle: "table table-bordered table-hover text-center",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
          columns: new[]  // colums in grid
         {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1),
            grid.Column("MA_VATTU","Mã vật tư"), //the model fields to display
            grid.Column("TEN_VATTU","Tên vật tư"),
            grid.Column("Thao tác", format: @<text>
    <a href="@Url.Action("Edit", new { id = item.MA_VATTU})" class="btn btn-sm btn-warning">Sửa</a>
    <a href="@Url.Action("Details", new { id = item.MA_VATTU})" class="btn btn-sm btn-info">Xem chi tiết</a>
    <a href="@Url.Action("Delete",new { id = item.MA_VATTU})" class="btn btn-sm btn-danger">Xóa</a>
            </text>),
}
)
</div>
}
else
{
    <b>Không tìm thấy vật tư nào</b>
}

QLKS_H2O/Areas/Admin/Views/VatTu/ThongKeVatTu.cshtml
@model IEnumerable<QLKS_H2O.Models.VATTU_LOAIPHONG>
@{
    ViewBag.Title = "ThongKeVatTu";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
}

<h2>Thống kê vật tư</h2>

<div class="mx-auto mb-3" style="width: 400px">
    @using (Html.BeginForm())
    {
        <div class="d-flex align-items-center">
            @Html.DropDownList("loaiPhong", null, new { @class = "form-control" })

            <div class="ml-2">
                <button class="btn btn-success" type="submit">Xem</button>
            </div>

        </div>
    }
</div>

@if (Model.Count() > 0)
{
    <table class="table table-striped text-center table-sm w-50 mx-auto">
        <tr>
            <th>
                Tên vật tư
            </th>
            <th>
                Số lượng
            </th>
            <th>
                Thao tác
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.VATTU.TEN_VATTU)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SOLUONG)
                </td>
                <td>
                    @Html.ActionLink("Sửa", "EditChiTiet", new { lp = item.MA_LOAIPHONG, vt = item.MA_VATTU })

                </td>
            </tr>
        }

    </table>

}

QLKS_H2O/Areas/Admin/Views/VatTu/TrangThaiPhong.cshtml
@model IEnumerable<QLKS_H2O.Models.PHONG>

@{
    ViewBag.Title = "TrangThaiPhong";
    Layout = "~/Areas/Admin/Views/Shared/_VatTuLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, rowsPerPage: 7);
}


<div>
    @using (Html.BeginForm("TrangThaiPhong", "VatTu", FormMethod.Get))
    {
        <table align="center" class="table1">
            <tr>
                <td>
                    <div> Mã phòng</div>
                </td>
                <td>
                    <input type="text" name="maP" value="@ViewBag.maP" class="form-control" />
                </td>

            </tr>
            <tr>
                <td></td>
                <td>
                    <button type="submit" class="btn btn-sm btn-primary">Tìm kiếm</button>
                    <a href="/Admin/VatTu/TrangThaiPhong" role="button" class="btn btn-sm btn-primary">Nhập mới</a>

                </td>
            </tr>
        </table>
    }
</div>

@if (Model.Count() > 0)
{
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover text-center",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
             {
                grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1),
                grid.Column("MA_PHONG","Mã phòng"), //the model fields to display
                grid.Column("TRANGTHAI_PHONG.TEN_TRANGTHAI","Trạng thái phòng"),
                grid.Column("Thao tác", format: @<text>
    <a href="@Url.Action("CapNhatTrangThaiPhong", new { maP = item.MA_PHONG, maTT = item.TRANGTHAI_PHONG.MA_TRANGTHAI})" class="btn btn-sm btn-warning">Cập nhật</a>
                </text>),
}
)
    </div>
}
else
{
    <b>Không có phòng nào được tìm thấy</b>
}