QLKS_H2O/Areas/Admin/Controllers/QuanLyController.cs
using QLKS_H2O.Areas.Admin.Models;
using QLKS_H2O.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QLKS_H2O.Areas.Admin.Controllers
{
    public class QuanLyController : BaseController
    {
        private QLKS_H2OEntities db = new QLKS_H2OEntities();

        // GET: LOAIPHONGs
        public ActionResult LoaiPhongIndex(string maLP = "", string tenLP = "")
        {
            ViewBag.tag = "loaiphong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            ViewBag.maLP = maLP;
            ViewBag.tenLP = tenLP;
            return View(
                db.LOAIPHONGs
                    .Where(lp => (lp.MA_LOAIPHONG == maLP || maLP == "") && 
                        (lp.TEN_LOAIPHONG.Contains(tenLP) || tenLP == ""))
            );
        }

        // GET: LOAIPHONGs/Details/5
        //public ActionResult LoaiPhongDetails(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    LOAIPHONG lOAIPHONG = db.LOAIPHONGs.Find(id);
        //    if (lOAIPHONG == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(lOAIPHONG);
        //}

        // GET: LOAIPHONGs/Create
        public ActionResult LoaiPhongCreate()
        {
            ViewBag.tag = "loaiphong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View();
        }

        // POST: LOAIPHONGs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoaiPhongCreate([Bind(Include = "MA_LOAIPHONG,TEN_LOAIPHONG,KICHTHUOC,MAMAU,ANH")] LOAIPHONG lOAIPHONG)
        {
            var img = Request.Files["ANH"];
            string postedFileName = System.IO.Path.GetFileName(img.FileName);
            var path = Server.MapPath("/Images/" + postedFileName);
            img.SaveAs(path);

            if (ModelState.IsValid)
            {
                int count = db.LOAIPHONGs.Where(phong => phong.MA_LOAIPHONG == lOAIPHONG.MA_LOAIPHONG).Count();

                if (count == 0)
                {
                    lOAIPHONG.ANH = postedFileName;
                    db.LOAIPHONGs.Add(lOAIPHONG);
                    db.SaveChanges();
                    return RedirectToAction("LoaiPhongIndex");
                }
                else
                {
                    ModelState.AddModelError("", "Loại phòng đã tồn tại");
                }
            }
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            ViewBag.tag = "loaiphong";
            return View(lOAIPHONG);
        }

        // GET: LOAIPHONGs/Edit/5
        public ActionResult LoaiPhongEdit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIPHONG lOAIPHONG = db.LOAIPHONGs.Find(id);
            if (lOAIPHONG == null)
            {
                return HttpNotFound();
            }
            ViewBag.tag = "loaiphong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(lOAIPHONG);
        }

        // POST: LOAIPHONGs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoaiPhongEdit([Bind(Include = "MA_LOAIPHONG,TEN_LOAIPHONG,KICHTHUOC,MAMAU,ANH")] LOAIPHONG lOAIPHONG)
        {
            if (ModelState.IsValid)
            {
                var img = Request.Files["ANH"];
                if (img != null)
                {
                    string postedFileName = System.IO.Path.GetFileName(img.FileName);
                    var path = Server.MapPath("/Images/" + postedFileName);
                    img.SaveAs(path);
                    lOAIPHONG.ANH = postedFileName;
                }
                
                db.Entry(lOAIPHONG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("LoaiPhongIndex");
            }
            ViewBag.tag = "loaiphong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(lOAIPHONG);
        }

        // GET: LOAIPHONGs/Delete/5
        public ActionResult LoaiPhongDelete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIPHONG lOAIPHONG = db.LOAIPHONGs.Find(id);
            if (lOAIPHONG == null)
            {
                return HttpNotFound();
            }
            ViewBag.tag = "loaiphong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(lOAIPHONG);
        }

        // POST: LOAIPHONGs/Delete/5
        [HttpPost, ActionName("LoaiPhongDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult LoaiPhongDeleteConfirmed(string id)
        {
            LOAIPHONG lOAIPHONG = db.LOAIPHONGs.Find(id);
            db.LOAIPHONGs.Remove(lOAIPHONG);
            db.SaveChanges();
            return RedirectToAction("LoaiPhongIndex");
        }


        // Phòng
        // GET: PHONG_QL
        public ActionResult PhongIndex(string maP = "")
        {
            var pHONGs = db.PHONGs.Include(p => p.LOAIPHONG).Include(p => p.TRANGTHAI_PHONG);
            ViewBag.tag = "phong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            ViewBag.maP = maP;
            return View(pHONGs.Where(p => p.MA_PHONG == maP || maP == "").ToList());
        }

        // GET: PHONG_QL/Details/5
        //public ActionResult PhongDetails(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    PHONG pHONG = db.PHONGs.Find(id);
        //    if (pHONG == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(pHONG);
        //}

        // GET: PHONG_QL/Create
        public ActionResult PhongCreate()
        {
            ViewBag.MA_LOAIPHONG = new SelectList(db.LOAIPHONGs, "MA_LOAIPHONG", "TEN_LOAIPHONG");
            ViewBag.MA_TRANGTHAI = new SelectList(db.TRANGTHAI_PHONG, "MA_TRANGTHAI", "TEN_TRANGTHAI");
            ViewBag.tag = "phong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View();
        }

        // POST: PHONG_QL/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PhongCreate([Bind(Include = "MA_PHONG,MA_LOAIPHONG,GIAPHONG,MA_TRANGTHAI")] PHONG pHONG)
        {
            if (ModelState.IsValid)
            {
                int count = db.PHONGs.Where(phong => phong.MA_PHONG == pHONG.MA_PHONG).Count();

                if (count == 0)
                {
                    db.PHONGs.Add(pHONG);
                    db.SaveChanges();
                    return RedirectToAction("PhongIndex");
                }
                else
                {
                    ModelState.AddModelError("", "Phòng đã tồn tại");
                }
            }

            ViewBag.MA_LOAIPHONG = new SelectList(db.LOAIPHONGs, "MA_LOAIPHONG", "TEN_LOAIPHONG", pHONG.MA_LOAIPHONG);
            ViewBag.MA_TRANGTHAI = new SelectList(db.TRANGTHAI_PHONG, "MA_TRANGTHAI", "TEN_TRANGTHAI", pHONG.MA_TRANGTHAI);
            ViewBag.tag = "phong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(pHONG);
        }

        // GET: PHONG_QL/Edit/5
        public ActionResult PhongEdit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PHONG pHONG = db.PHONGs.Find(id);
            if (pHONG == null)
            {
                return HttpNotFound();
            }
            ViewBag.MA_LOAIPHONG = new SelectList(db.LOAIPHONGs, "MA_LOAIPHONG", "TEN_LOAIPHONG", pHONG.MA_LOAIPHONG);
            ViewBag.MA_TRANGTHAI = new SelectList(db.TRANGTHAI_PHONG, "MA_TRANGTHAI", "TEN_TRANGTHAI", pHONG.MA_TRANGTHAI);
            ViewBag.tag = "phong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(pHONG);
        }

        // POST: PHONG_QL/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PhongEdit([Bind(Include = "MA_PHONG,MA_LOAIPHONG,GIAPHONG,MA_TRANGTHAI")] PHONG pHONG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pHONG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("PhongIndex");
            }
            ViewBag.MA_LOAIPHONG = new SelectList(db.LOAIPHONGs, "MA_LOAIPHONG", "TEN_LOAIPHONG", pHONG.MA_LOAIPHONG);
            ViewBag.MA_TRANGTHAI = new SelectList(db.TRANGTHAI_PHONG, "MA_TRANGTHAI", "TEN_TRANGTHAI", pHONG.MA_TRANGTHAI);
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;

QLKS_H2O/Areas/Admin/Views/QuanLy/DichVuDelete.cshtml
@model QLKS_H2O.Models.DICHVU

@{
    ViewBag.Title = "DichVuDelete";
    Layout = "~/Areas/Admin/Views/Shared/_QuanLyLayout.cshtml";
}

<h3>Bạn có chắc chắn xóa dịch vụ này không?</h3>
<div>
    <h4>Thông tin dịch vụ</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MA_DICHVU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MA_DICHVU)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TEN_DICHVU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEN_DICHVU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GIA_DICHVU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIA_DICHVU)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Quay lại", "DichVuIndex")
        </div>
    }
</div>

QLKS_H2O/Areas/Admin/Views/QuanLy/DichVuDetails.cshtml
@model QLKS_H2O.Models.DICHVU

@{
    ViewBag.Title = "DichVuDetails";
    Layout = "~/Areas/Admin/Views/Shared/_QuanLyLayout.cshtml";
}

<h2>DichVuDetails</h2>

<div>
    <h4>DICHVU</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TEN_DICHVU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEN_DICHVU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GIA_DICHVU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIA_DICHVU)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "DichVuEdit", new { id = Model.MA_DICHVU }) |
    @Html.ActionLink("Quay lại", "DichVuIndex")
</p>

QLKS_H2O/Areas/Admin/Views/QuanLy/DichVuEdit.cshtml
@model QLKS_H2O.Models.DICHVU

@{
    ViewBag.Title = "DichVuEdit";
    Layout = "~/Areas/Admin/Views/Shared/_QuanLyLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal w-75 mx-auto">
    <h4>Thông tin dịch vụ</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MA_DICHVU)

    <div class="form-group d-flex align-items-center">
        @Html.LabelFor(model => model.MA_DICHVU, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MA_DICHVU, new { htmlAttributes = new { @class = "form-control form-control-sm", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.TEN_DICHVU, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group d-flex align-items-center">
        @Html.LabelFor(model => model.TEN_DICHVU, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TEN_DICHVU, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
            @Html.ValidationMessageFor(model => model.TEN_DICHVU, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group d-flex align-items-center">
        @Html.LabelFor(model => model.GIA_DICHVU, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GIA_DICHVU, new { htmlAttributes = new { @class = "form-control form-control-sm", @type = "number" } })
            @Html.ValidationMessageFor(model => model.GIA_DICHVU, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "DichVuIndex")
</div>

QLKS_H2O/Areas/Admin/Views/QuanLy/LoaiPhongCreate.cshtml
@model QLKS_H2O.Models.LOAIPHONG

@{
    ViewBag.Title = "Loại phòng";
    Layout = "~/Areas/Admin/Views/Shared/_QuanLyLayout.cshtml";
}

    <h3 class="text-center my-2"> Thêm Mới Loại Phòng</h3>

@using (Html.BeginForm("LoaiPhongCreate", "QuanLy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal w-75 mx-auto">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group d-flex align-items-center">
        @Html.LabelFor(model => model.MA_LOAIPHONG, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MA_LOAIPHONG, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
            @Html.ValidationMessageFor(model => model.MA_LOAIPHONG, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group d-flex align-items-center">
        @Html.LabelFor(model => model.TEN_LOAIPHONG, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TEN_LOAIPHONG, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
            @Html.ValidationMessageFor(model => model.TEN_LOAIPHONG, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group d-flex align-items-center">
        @Html.LabelFor(model => model.KICHTHUOC, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KICHTHUOC, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
            @Html.ValidationMessageFor(model => model.KICHTHUOC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group d-flex align-items-center">
        @Html.LabelFor(model => model.MAMAU, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MAMAU, new { htmlAttributes = new { @class = "form-control form-control-sm w-25", @type = "color" } })
            @Html.ValidationMessageFor(model => model.MAMAU, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group d-flex align-items-center">
        @Html.LabelFor(model => model.ANH, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ANH" accept="image/*" required class="form-control form-control-sm" />
            @Html.ValidationMessageFor(model => model.ANH, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "LoaiPhongIndex")
</div>

QLKS_H2O/Areas/Admin/Views/QuanLy/LoaiPhongEdit.cshtml
@model QLKS_H2O.Models.LOAIPHONG

@{
    ViewBag.Title = "LoaiPhongEdit";
    Layout = "~/Areas/Admin/Views/Shared/_QuanLyLayout.cshtml";
}

@using (Html.BeginForm("LoaiPhongEdit", "QuanLy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal w-75 mx-auto">
        <h4>Thông tin loại phòng</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MA_LOAIPHONG)

        <div class="form-group d-flex align-items-center">
            @Html.LabelFor(model => model.MA_LOAIPHONG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MA_LOAIPHONG, new { htmlAttributes = new { @class = "form-control form-control-sm", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MA_LOAIPHONG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex align-items-center">
            @Html.LabelFor(model => model.TEN_LOAIPHONG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEN_LOAIPHONG, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.TEN_LOAIPHONG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex align-items-center">
            @Html.LabelFor(model => model.KICHTHUOC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KICHTHUOC, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.KICHTHUOC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex align-items-center">
            @Html.LabelFor(model => model.MAMAU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="MAMAU" name="MAMAU" type="color" class="w-25 form-control form-control-sm" value="@Model.MAMAU" />
                @Html.ValidationMessageFor(model => model.MAMAU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex align-items-center">
            @Html.LabelFor(model => model.ANH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ANH" accept="image/*" required class="form-control form-control-sm" />
                @Html.ValidationMessageFor(model => model.ANH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "LoaiPhongIndex")
</div>

QLKS_H2O/Areas/Admin/Views/QuanLy/LoaiPhongIndex.cshtml
@model IEnumerable<QLKS_H2O.Models.LOAIPHONG>

@{
    ViewBag.Title = "Loại phòng";
    Layout = "~/Areas/Admin/Views/Shared/_QuanLyLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, rowsPerPage: 7);
}

<h3 class="text-center my-2">Danh Sách Loại Phòng</h3>
<p>@Html.ActionLink("Thêm mới", "LoaiPhongCreate")</p>

<div>
    @using (Html.BeginForm("LoaiPhongIndex", "QuanLy", FormMethod.Get))
    {
        <table align="center" class="table1">
            <tr>
                <td>
                    <div> Mã loại phòng</div>
                </td>
                <td>
                    <input type="text" name="maLP" value="@ViewBag.maLP" class="form-control" />
                </td>

            </tr>
            <tr>
                <td>Tên loại phòng</td>
                <td>
                    <input type="text" name="tenLP" value="@ViewBag.tenLP" class="form-control" />
                </td>

            </tr>
            <tr>
                <td></td>
                <td>
                    <button type="submit" class="btn btn-sm btn-primary">Tìm kiếm</button>
                    <a href="/Admin/QuanLy/LoaiPhongIndex" role="button" class="btn btn-sm btn-primary">Nhập mới</a>

                </td>
            </tr>
        </table>
    }
</div>

@if (Model.Count() > 0)
{
<div id="gridContent">
    @ViewBag.TB
    @grid.GetHtml(
        tableStyle: "table table-bordered table-hover text-center",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
          columns: new[]  // colums in grid
         {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1),
            grid.Column("MA_LOAIPHONG","Mã Loại Phòng"), //the model fields to display
            grid.Column("TEN_LOAIPHONG","Tên Loại Phòng"),
            grid.Column("KICHTHUOC","Kích thước"),
            grid.Column("MAMAU", "Mã Màu", format: @<text>
    <input type="color" value="@item.MAMAU" disabled />
            </text>),
       grid.Column("ANH", "Ảnh", format: @<text>
                <img src="/Images/@item.ANH" width="100px" />
    </text>),
grid.Column("Thao tác", format: @<text>
        <a href="@Url.Action("LoaiPhongEdit", new { id = item.MA_LOAIPHONG})" class="btn btn-sm btn-warning">Sửa</a>
        <a href="@Url.Action("LoaiPhongDelete",new { id = item.MA_LOAIPHONG})" class="btn btn-sm btn-danger">Xóa</a>
</text>),
}
)
</div>
}
else
{
    <b>Không có loại phòng nào được tìm thấy</b>
}

QLKS_H2O/Areas/Admin/Views/QuanLy/PhongIndex.cshtml
@model IEnumerable<QLKS_H2O.Models.PHONG>

@{
    ViewBag.Title = "PhongIndex";
    Layout = "~/Areas/Admin/Views/Shared/_QuanLyLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, rowsPerPage: 7);
}

<h3 class="text-center my-2">Danh Sách Phòng</h3>

<p>@Html.ActionLink("Thêm mới Phòng ", "PhongCreate")</p>
<div>
    @using (Html.BeginForm("PhongIndex", "QuanLy", FormMethod.Get))
    {
        <table align="center" class="table1">
            <tr>
                <td>
                    <div> Mã phòng</div>
                </td>
                <td>
                    <input type="text" name="maP" value="@ViewBag.maP" class="form-control" />
                </td>

            </tr>
            <tr>
                <td></td>
                <td>
                    <button type="submit" class="btn btn-sm btn-primary">Tìm kiếm</button>
                    <a href="/Admin/QuanLy/PhongIndex" role="button" class="btn btn-sm btn-primary">Nhập mới</a>

                </td>
            </tr>
        </table>
    }
</div>

@if (Model.Count() > 0)
{
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover text-center",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
             {
                grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1),
                grid.Column("MA_PHONG","Mã Phòng"), //the model fields to display
                grid.Column("LOAIPHONG.TEN_LOAIPHONG","Loại Phòng"),
                grid.Column("GIAPHONG","Giá Phòng"),
                grid.Column("Thao tác", format: @<text>
    <a href="@Url.Action("PhongEdit", new { id = item.MA_PHONG})" class="btn btn-sm btn-warning">Sửa</a>
    <a href="@Url.Action("PhongDelete",new { id = item.MA_PHONG})" class="btn btn-sm btn-danger">Xóa</a>
                </text>),
}
)
    </div>
}
else
{
    <b>Không có phòng nào được tìm thấy</b>
}