QLKS_H2O/Models/PHIEU_THUEPHONG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PHIEU_THUEPHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_THUEPHONG()
        {
            this.CHITIET_THUEDICHVU = new HashSet<CHITIET_THUEDICHVU>();
            this.CHITIET_THUEPHONG = new HashSet<CHITIET_THUEPHONG>();
        }

        [DisplayName("Số phiếu")]
        [Required(ErrorMessage = "Chưa nhập số phiếu")]
        public string SO_PHIEU { get; set; }
        [DisplayName("Khách thuê")]
        [Required(ErrorMessage = "Chưa nhập mã khách")]
        public string MAKHACH { get; set; }
        [DisplayName("Nhân viên")]
        [Required(ErrorMessage = "Chưa nhập nhân viên")]
        public string MA_NHANVIEN { get; set; }
        [DisplayName("Ngày lập phiếu")]
        [Required(ErrorMessage = "Chưa nhập ngày lập phiếu")]
        public System.DateTime NGAYLAP_PHIEU { get; set; }
        [DisplayName("Ngày đến")]
        [Required(ErrorMessage = "Chưa nhập ngày đến")]
        public System.DateTime NGAYDEN { get; set; }
        [DisplayName("Ngày đi")]
        [Required(ErrorMessage = "Chưa nhập ngày đi")]
        public System.DateTime NGAYDI { get; set; }
        [DisplayName("Đã trả phòng")]
        public Nullable<bool> DATRAPHONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_THUEDICHVU> CHITIET_THUEDICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_THUEPHONG> CHITIET_THUEPHONG { get; set; }
        public virtual KHACH KHACH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}

QLKS_H2O/Models/PHONG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.CHITIET_THUEPHONG = new HashSet<CHITIET_THUEPHONG>();
        }

        [DisplayName("Mã phòng")]
        [Required(ErrorMessage = "Chưa nhập mã phòng")]
        public string MA_PHONG { get; set; }
        [DisplayName("Loại phòng")]
        public string MA_LOAIPHONG { get; set; }
        [DisplayName("Giá phòng")]
        [Required(ErrorMessage = "Chưa nhập giá phòng")]
        [Range(0, double.MaxValue, ErrorMessage = "Giá phòng phải lớn hơn 0")]
        public decimal GIAPHONG { get; set; }
        [DisplayName("Trạng thái phòng")]
        public string MA_TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_THUEPHONG> CHITIET_THUEPHONG { get; set; }
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        public virtual TRANGTHAI_PHONG TRANGTHAI_PHONG { get; set; }
    }
}

QLKS_H2O/Areas/Admin/Controllers/LeTanController.cs
using QLKS_H2O.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLKS_H2O.Areas.Admin.Models;
using System.Net;
using System.Data.Entity;
using SelectPdf;
using Microsoft.Ajax.Utilities;

namespace QLKS_H2O.Areas.Admin.Controllers
{
    public class LeTanController : BaseController
    {
        private QLKS_H2OEntities db = new QLKS_H2OEntities();

        // GET: Admin/LeTan
        // Danh sách phòng + tìm kiếm phòng theo tiêu chí
        public ActionResult Index(string maphong = "", string tang = "", string trangthai = "", string loaiphong = "",
            double giatu = 0, double giaden = Double.MaxValue)
        {
            char soTang = tang != "" ? tang.ToCharArray()[0] : '_';
            List<PhongModel> phongs = db.PHONGs
                .Where(phong => (phong.MA_PHONG == maphong || maphong == "")
                            && (phong.MA_TRANGTHAI == trangthai || trangthai == "")
                            && (phong.MA_LOAIPHONG == loaiphong || loaiphong == "")
                            && ((double)phong.GIAPHONG >= giatu)
                            && ((double)phong.GIAPHONG <= giaden)
                            && (phong.MA_PHONG.Substring(0, 1) == tang || tang == "")
                            )
                .Select(phong => new PhongModel()
                {
                    maPhong = phong.MA_PHONG,
                    mauLoaiPhong = phong.LOAIPHONG.MAMAU,
                    mauTrangThai = phong.TRANGTHAI_PHONG.MAMAU,
                    giaPhong = (decimal)phong.GIAPHONG
                })
                .ToList();

            var groupPhongs = phongs.Aggregate(new List<PhongGroupModel>(), (acc, cur) =>
            {
                PhongGroupModel t = acc.Find(group => group.tang == cur.maPhong[0].ToString());
                if (t == null)
                {
                    acc.Add(new PhongGroupModel()
                    {
                        tang = cur.maPhong[0].ToString(),
                        phongs = new List<PhongModel>() { cur }
                    });
                }
                else
                {
                    t.phongs.Add(cur);
                }
                return acc;
            });

            List<LOAIPHONG> loaiPhongs = db.LOAIPHONGs.ToList();
            ViewBag.loaiPhongs = loaiPhongs;

            List<TRANGTHAI_PHONG> trangThais = db.TRANGTHAI_PHONG.ToList();
            ViewBag.trangThais = trangThais;

            ViewBag.maphong = maphong;
            ViewBag.tang = tang;
            ViewBag.trangthai = trangthai;
            ViewBag.loaiphong = loaiphong;
            ViewBag.giatu = giatu;
            ViewBag.giaden = giaden;

            ViewBag.tag = "phong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(groupPhongs);
        }

        // GET: /Admin/LaTan/Phong/:idPhong
        // Hiển thị thông tin chi tiết của 1 phòng
        public ActionResult Phong(string id)
        {
            PHONG phong = db.PHONGs.Find(id);
            var phieus = db.CHITIET_THUEPHONG.Where(ct => ct.MAPHONG == id && ct.PHIEU_THUEPHONG.DATRAPHONG == false).ToList();
            if (phieus.Count() > 0)
            {
                ViewBag.phieuThue = phieus[0].PHIEU_THUEPHONG;
            }
            ViewBag.tag = "phong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(phong);
        }

        // GET: /Admin/LaTan/DanhSachPhieuThue
        // Danh sách phiếu thuê phòng
        public ActionResult DanhSachPhieuThue(string soPhieu = "", string tenK = "")
        {
            ViewBag.tag = "thuephong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            ViewBag.soPhieu = soPhieu;
            ViewBag.tenK = tenK;
            return View(
                db.PHIEU_THUEPHONG
                    .Where(ph => (ph.SO_PHIEU == soPhieu || soPhieu == "") && 
                        (ph.KHACH.HOTEN_KHACH.Contains(tenK) || tenK == ""))
                    .OrderBy(phieu => phieu.DATRAPHONG)
                    .ThenByDescending(phieu => phieu.NGAYDEN)
            );
        }

        // GET: /Admin/LaTan/ThemPhieuThuePhong
        // View thuê phòng
        public ActionResult ThemPhieuThuePhong()
        {
            ViewBag.phong = db.PHONGs.Where(phong => phong.MA_TRANGTHAI == "VC").ToList();
            ViewBag.dichVus = new SelectList(db.DICHVUs, "MA_DICHVU", "TEN_DICHVU");

            ViewBag.tag = "thuephong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View();
        }

        // POST: /Admin/LaTan/ThemPhieuThuePhong
        // thuê phòng
        [HttpPost]
        public ActionResult ThemPhieuThuePhong(FormCollection form)
        {
            string tenKhach = form["tenkhach"];
            string cmnd = form["cmnd"];
            string ngaySinh = form["ngaysinh"];
            string gioiTinh = form["gioitinh"];
            string dienThoai = form["dienthoai"];
            string quocTich = form["quoctich"];
            string ngayDi = form["ngaydi"];
            string phongs = form["phong"];
            string soNguois = form["songuoi"];
            string dichVus = form["dichvu"];
            string soLuongs = form["soluong"];

            string maKhach = Math.Round(((new Random()).NextDouble() * 1e9)).ToString().PadLeft(9, '0');
                string soPhieu = Math.Round(((new Random()).NextDouble() * 1e9)).ToString().PadLeft(9, '0');

                List<String> phongList = phongs.Split(new[] { ',' }).ToList();
                List<String> soNguoiList = soNguois.Split(new[] { ',' }).ToList();
                List<String> dichVuList = dichVus != null ? dichVus.Split(new[] { ',' }).ToList() : new List<string>();
                List<String> soLuongList = soLuongs != null ? soLuongs.Split(new[] { ',' }).ToList() : new List<string>();

                PHIEU_THUEPHONG phieu = new PHIEU_THUEPHONG()
                {
                    SO_PHIEU = soPhieu,
                    MAKHACH = maKhach,
                    KHACH = new KHACH()
                    {
                        MA_KHACH = maKhach,
                        CMND = cmnd,
                        DIENTHOAI = dienThoai,
                        HOTEN_KHACH = tenKhach,
                        QUOCTICH = quocTich,
                        GIOITINH = gioiTinh == "1" ? true : false,
                        NGAYSINH = DateTime.Parse(ngaySinh)
                    },
                    DATRAPHONG = false,
                    NGAYDEN = DateTime.Now,
                    NGAYLAP_PHIEU = DateTime.Now,
                    NGAYDI = DateTime.Parse(ngayDi),
                    MA_NHANVIEN = ((LoginSessionModel)Session["session"]).username,
                    CHITIET_THUEPHONG = phongList.Select((p, index) => new CHITIET_THUEPHONG()
                    {
                        SO_PHIEU = soPhieu,
                        MAPHONG = p,
                        SONGUOI = Byte.Parse(soNguoiList[index]),
                        GIAPHONG = db.PHONGs.Find(p).GIAPHONG,
                    }).ToList(),
                    CHITIET_THUEDICHVU = dichVuList.Select((dv, index) => new CHITIET_THUEDICHVU()
                    {
                        SO_PHIEU = soPhieu,
                        MA_DICHVU = dv,
                        SOLUONG = Byte.Parse(soLuongList[index]),
                        GIA_DICHVU = db.DICHVUs.Find(dv).GIA_DICHVU,
                    }).ToList(),
                };

                db.PHIEU_THUEPHONG.Add(phieu);

                phongList.ForEach(p => db.PHONGs.Find(p).MA_TRANGTHAI = "OC");

                db.SaveChanges();

                return RedirectToAction("DanhSachPhieuThue");
            

            //ViewBag.phong = db.PHONGs.Where(p => p.MA_TRANGTHAI == "VC").ToList();
            //ViewBag.dichVus = new SelectList(db.DICHVUs, "MA_DICHVU", "TEN_DICHVU");

            //ViewBag.tag = "thuephong";
            //ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            //return View();
        }

        // GET: /Admin/LeTan/PhieuThuePhong/:id
        // Xem thông tin phiếu thuê phòng
        public ActionResult PhieuThuePhong(string id)
        {
            ViewBag.tag = "thuephong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(db.PHIEU_THUEPHONG.Find(id));
        }

        // GET: /Admin/LeTan/XoaPhieuThuePhong/:id
        // Xác nhận xóa phiếu thuê phòng
        public ActionResult XoaPhieuThuePhong(string id)
        {
            ViewBag.tag = "thuephong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(db.PHIEU_THUEPHONG.Find(id));
        }

        // POST: /Admin/LeTan/XoaPhieuThuePhong/:id
        [HttpPost, ActionName("XoaPhieuThuePhong")]
        public ActionResult XoaPhieuThuePhongConfirmed(string id)
        {
            PHIEU_THUEPHONG phieu = db.PHIEU_THUEPHONG.Find(id);
            db.PHIEU_THUEPHONG.Remove(phieu);
            db.SaveChanges();
            return RedirectToAction("DanhSachPhieuThue");
        }

        // GET: /Admin/LeTan/SuaPhieuThuePhong/:id
        // View cập nhật phiếu thuê phòng
        public ActionResult SuaPhieuThuePhong(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PHIEU_THUEPHONG phieu = db.PHIEU_THUEPHONG.Find(id);
            if (phieu == null)
            {
                return HttpNotFound();
            }

            ViewBag.tag = "thuephong";
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(phieu);
        }

        // POST: /Admin/LeTan/SuaPhieuThuePhong
        // Cập nhật phiếu thuê phòng
        [HttpPost]

QLKS_H2O/Areas/Admin/Views/LeTan/CreateHoaDon.cshtml
@model QLKS_H2O.Models.PHIEU_THUEPHONG

@{
    Layout = null;
    int indexPhong = 0;
    int indexDichVu = 0;
    decimal tienPhong = 0;
    decimal tienDichVu = 0;
    decimal tienTra = 0;
    int soNgay = (int)((Model.NGAYDI - Model.NGAYDEN).Ticks / 864e9);
    if (soNgay <= 0)
    {
        soNgay = 1;
    }

    // chuyển từ số sang dạn word: 100 -> một trăm
    string NumberToWords(int number)
    {
        if (number == 0) return "không";

        if (number < 0) return "âm " + NumberToWords(Math.Abs(number));

        string words = "";

        if ((number / 1000000) > 0)
        {
            words += NumberToWords(number / 1000000) + " triệu ";
            number %= 1000000;
        }

        if ((number / 1000) > 0)
        {
            words += NumberToWords(number / 1000) + " nghìn ";
            number %= 1000;
        }

        if ((number / 100) > 0)
        {
            words += NumberToWords(number / 100) + " trăm ";
            number %= 100;
        }

        if (number > 0)
        {
            var unitsMap = new[] { "không", "một", "hai", "ba", "bốn", "năm", "sáu", "bảy", "tám", "chín", "mười" };
            var tensMap = new[] { "không", "mười", "hai mươi", "ba mươi", "bốn mươi", "năm mươi", "sáu mươi", "bảy mươi", "tám mươi", "chín mươi" };

            if (number < 10)
                words += unitsMap[number];
            else
            {
                words += tensMap[number / 10];
                if ((number % 10) > 0)
                    words += " " + unitsMap[number % 10];
            }
        }

        return words;
    }
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateHoaDon</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="mx-auto p-3" style="width: 760px;">
        <div class="d-flex px-5">
            <div class="flex-fill">
                <img src="/Images/logo.png" alt="H2O" width="200px" />
            </div>
            <div class="flex-fill pl-5">
                <div>
                    <h4>KHÁCH SẠN H2O</h4>
                </div>
                <div>
                    <b>Địa chỉ: 39 Yết Kiêu, Hòa Thắng, Phú Hòa, Phú Yên</b>
                </div>
                <div>
                    <b>Điện thoại: 03698548754</b>
                </div>
            </div>
        </div>
        <h3 class="text-center mt-4">HÓA ĐƠN THANH TOÁN</h3>
        <div class="p-4">
            <table class="table table-sm table-borderless">
                <tr>
                    <th>Họ và tên khách hàng</th>
                    <td>@Model.KHACH.HOTEN_KHACH</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>CMND/PASSPORT</th>
                    <td>@Model.KHACH.CMND</td>
                    <th>Quốc tịch</th>
                    <td>@Model.KHACH.QUOCTICH</td>
                </tr>
                <tr>
                    <th>Điện thoại</th>
                    <td>@Model.KHACH.DIENTHOAI</td>
                    <td></td>
                    <td></td>
                </tr>
            </table>

            <b>Chi tiết sử dụng phòng</b>
            <table class="table table-sm text-center table-bordered">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Phòng</th>
                        <th>Loại phòng</th>
                        <th>Số ngày</th>
                        <th>Đơn giá (một đêm)</th>
                        <th>Thành tiền</th>
                    </tr>
                </thead>
                <tbody id="phongBody">
                    @foreach (var ctThuePhong in Model.CHITIET_THUEPHONG)
                    {
                        <tr>
                            <td>
                                @{indexPhong++;}
                                @indexPhong
                            </td>
                            <td>@ctThuePhong.MAPHONG</td>
                            <td>@ctThuePhong.PHONG.LOAIPHONG.TEN_LOAIPHONG</td>
                            <td>@soNgay</td>
                            <td>@(String.Format("{0,1:N1}", ctThuePhong.GIAPHONG))đ</td>
                            <td>@(String.Format("{0,1:N1}", ctThuePhong.GIAPHONG * (decimal)soNgay))đ</td>
                            @{ tienPhong += (decimal)ctThuePhong.GIAPHONG * (decimal)soNgay;}

                        </tr>
                    }
                    <tr>
                        <td colspan="5">
                            <b>Tổng cộng</b>
                        </td>
                        <td>@(String.Format("{0,1:N1}", tienPhong))đ</td>
                    </tr>
                </tbody>
            </table>

            <b>Chi tiết sử dụng dịch vụ</b>
            <table class="table table-sm text-center table-bordered">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Dịch vụ</th>
                        <th>Số lượng</th>
                        <th>Đơn giá</th>
                        <th>Thành tiền</th>
                    </tr>
                </thead>
                <tbody id="dichVuBody">
                    @foreach (var ctThueDV in Model.CHITIET_THUEDICHVU)
                    {
                        <tr>
                            <td>
                                @{indexDichVu++;}
                                @indexDichVu
                            </td>
                            <td>@ctThueDV.DICHVU.TEN_DICHVU</td>
                            <td>@ctThueDV.SOLUONG</td>
                            <td>@(String.Format("{0,1:N1}", ctThueDV.GIA_DICHVU))đ</td>
                            <td>@(String.Format("{0,1:N1}", ctThueDV.GIA_DICHVU * ctThueDV.SOLUONG))đ</td>
                            @{ tienDichVu += (decimal)ctThueDV.GIA_DICHVU * ctThueDV.SOLUONG;}
                        </tr>
                    }
                    <tr>
                        <td colspan="4">
                            <b>Tổng cộng</b>
                        </td>
                        <td>@(String.Format("{0,1:N1}", tienDichVu))đ</td>
                    </tr>
                </tbody>
            </table>

            <table class="table table-sm">
                <tr>
                    <th>Tổng tiền</th>
                    <td id="tien" class="text-right">@(String.Format("{0,1:N1}", tienPhong + tienDichVu))đ</td>
                </tr>
                <tr>
                    <th>Phí VAT</th>
                    <td class="text-right">10%</td>
                </tr>
                <tr>
                    <th>Tổng tiền thanh toán</th>
                    @{tienTra = ((decimal)(tienPhong + tienDichVu)) * (decimal)1.1;}
                    <td class="text-right">@String.Format("{0,1:N1}", tienTra)</td>
                </tr>
            </table>
            <div class="my-3">
                <b>Số tiền ghi bằng chữ: </b>
                <span>@NumberToWords((int)tienTra) đồng</span>
            </div>
            <div class="text-right pr-5 mb-3">
                <i>Ngày @(Model.NGAYDI.Day) tháng @(Model.NGAYDI.Month) năm @(Model.NGAYDI.Year)</i>
            </div>
            <div class="d-flex justify-content-around text-center">
                <div>
                    <b>Khách hàng</b>
                    <br />
                    <b>(Ký, họ tên)</b>
                </div>
                <div>
                    <b>Người lập phiếu</b>
                    <br />
                    <b>(Ký, họ tên)</b>
                    <br />
                    <span>@Model.NHANVIEN.HOTEN_NHANVIEN</span>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

QLKS_H2O/Areas/Admin/Views/LeTan/DanhSachPhieuThue.cshtml
@model IEnumerable<QLKS_H2O.Models.PHIEU_THUEPHONG>
@{
    ViewBag.Title = "Phiếu thuê phòng";
    Layout = "~/Areas/Admin/Views/Shared/_LeTanLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, rowsPerPage: 5);
}

@section letan_style {
    <link href="~/Content/footer-grid.css" rel="stylesheet" />
}

@Html.ActionLink("Thêm phiếu", "ThemPhieuThuePhong", null, new { @class = "btb btn-success btn-sm" })

<h4 class="text-center">DANH SÁCH PHIẾU THUÊ PHÒNG</h4>

<div>
    @using (Html.BeginForm("DanhSachPhieuThue", "LeTan", FormMethod.Get))
    {
        <table align="center" class="table1">
            <tr>
                <td>
                    <div>Số phiếu</div>
                </td>
                <td>
                    <input type="text" name="soPhieu" value="@ViewBag.soPhieu" class="form-control" />
                </td>

            </tr>
            <tr>
                <td>Tên khách hàng</td>
                <td>
                    <input type="text" name="tenK" value="@ViewBag.tenK" class="form-control" />
                </td>

            </tr>
            <tr>
                <td></td>
                <td>
                    <button type="submit" class="btn btn-sm btn-primary">Tìm kiếm</button>
                    <a href="/Admin/LeTan/DanhSachPhieuThue" role="button" class="btn btn-sm btn-primary">Nhập mới</a>

                </td>
            </tr>
        </table>
    }
</div>

@if (Model.Count() > 0)
{
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover table-striped text-center",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.All,
            columns: new[]  // colums in grid
            {
                grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
                grid.Column("SO_PHIEU","Số phiếu"), //the model fields to display
                grid.Column("NGAYLAP_PHIEU","Ngày lập phiếu", item => item.NGAYLAP_PHIEU.ToString("dd/MM/yyyy")),
                grid.Column("NGAYDEN","Ngày đến", item => item.NGAYDEN.ToString("dd/MM/yyyy")),
                grid.Column("NGAYDI","Ngày đi", item => item.NGAYDI.ToString("dd/MM/yyyy")),
                grid.Column("DATRAPHONG","Đã trả phòng", item => item.DATRAPHONG==true?"Đã":"Chưa"),
                grid.Column("KHACH.HOTEN_KHACH","Khách thuê"),
                grid.Column("NHANVIEN.HOTEN_NHANVIEN","Nhân viên lập phiếu"),
                grid.Column("Thao tác", format: @<text>
    @if(item.DATRAPHONG)
                {
    <a href="@Url.Action("XoaPhieuThuePhong", new { id = item.SO_PHIEU})" class="btn btn-sm btn-danger">Xóa</a>
                } else
                {
    <a href="@Url.Action("TraPhong", new { id = item.SO_PHIEU})" class="btn btn-sm btn-success">Trả phòng</a>
    <a href="@Url.Action("SuaPhieuThuePhong", new { id = item.SO_PHIEU})" class="btn btn-sm btn-secondary">Cập nhật</a>
                }
    <a href="@Url.Action("PhieuThuePhong", new { id = item.SO_PHIEU})" class="btn btn-sm btn-info">Xem</a>
                </text>),
     }
 )
    </div>

}
else
{
    <b>Không tìm thấy phiếu thuê phòng nào</b>
}