QLKS_H2O/Areas/Admin/Controllers/KeToanController.cs
using Microsoft.Ajax.Utilities;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using QLKS_H2O.Areas.Admin.Models;
using QLKS_H2O.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace QLKS_H2O.Areas.Admin.Controllers
{
    public class KeToanController : BaseController
    {
        private QLKS_H2OEntities db = new QLKS_H2OEntities();

        private List<HoaDonModel> FindHoaDon(string billid, string datecreate, double summin, double summax)
        {
            var phieuThues = db.PHIEU_THUEPHONG
                .ToList()
                .Where(phieu => (phieu.DATRAPHONG == true) &&
                    (phieu.SO_PHIEU == billid || billid == "")
                    &&
                    (datecreate == "" || phieu.NGAYDI.CompareTo(DateTime.Parse(datecreate)) == 0)
                );

            List<HoaDonModel> hoaDons = new List<HoaDonModel>();

            phieuThues.ForEach(phieu =>
            {
                HoaDonModel hoaDon = new HoaDonModel();
                hoaDon.maPhieu = phieu.SO_PHIEU;
                hoaDon.ngayDen = phieu.NGAYDEN;
                hoaDon.ngayDi = phieu.NGAYDI;

                decimal tp = 0;
                double soNgay = (phieu.NGAYDI - phieu.NGAYDEN).Ticks / 864e9;

                phieu.CHITIET_THUEPHONG.ForEach(ct =>
                {
                    tp += (decimal)soNgay * (decimal)ct.GIAPHONG;
                });

                hoaDon.tienPhong = tp;

                decimal tdv = 0;
                phieu.CHITIET_THUEDICHVU.ForEach(ct =>
                {
                    tdv += ct.SOLUONG * (decimal)ct.GIA_DICHVU;
                });

                hoaDon.tienDichVu = tdv;

                hoaDon.tongTien = tp + tdv;

                hoaDons.Add(hoaDon);
            });

            return hoaDons
                .AsEnumerable()
                .Where(hoaDon => (hoaDon.tongTien >= (decimal)summin) &&
                    ((double)hoaDon.tongTien <= summax)
                ).ToList();
        }

        // GET: Admin/KeToan
        public ActionResult Index(string billid = "", string datecreate = "", double summin = 0, double summax = Double.MaxValue)
        {
            List<HoaDonModel> hoaDons = FindHoaDon(billid, datecreate, summin, summax);

            ViewBag.billid = billid;
            ViewBag.summin = summin;
            ViewBag.summax = summax;
            ViewBag.datecreate = datecreate;
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(hoaDons);
        }

        public void DownloadHoaDon(string billid = "", string datecreate = "", double summin = 0, double summax = Double.MaxValue)
        {
            List<HoaDonModel> hoaDons = FindHoaDon(billid, datecreate, summin, summax);

            ExcelPackage ep = new ExcelPackage();
            ExcelWorksheet sheet = ep.Workbook.Worksheets.Add("HoaDon");

            for(int i = 1; i <= 7; i++)
            {
                sheet.Column(i).Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
            }
            sheet.Column(5).Style.Numberformat.Format = "#,##0.00";
            sheet.Column(6).Style.Numberformat.Format = "#,##0.00";
            sheet.Column(7).Style.Numberformat.Format = "#,##0.00";

            sheet.Row(1).Style.Font.Bold = true;
            sheet.Cells["A1:G1"].Merge = true;
            sheet.Cells["A1"].Value = "DANH SÁCH HÓA ĐƠN";

            sheet.Cells["A2"].Value = "STT";
            sheet.Cells["B2"].Value = "Mã phiếu";
            sheet.Cells["C2"].Value = "Ngày đến";
            sheet.Cells["D2"].Value = "Ngày đi";
            sheet.Cells["E2"].Value = "Tổng tiền phòng";
            sheet.Cells["F2"].Value = "Tổng tiền dịch vụ";
            sheet.Cells["G2"].Value = "Tổng tiền";
            sheet.Row(2).Style.Font.Bold = true;

            int row = 3;
            hoaDons.ForEach(hoaDon =>
            {
                sheet.Cells[$"A{row}"].Value = row - 2;
                sheet.Cells[$"B{row}"].Value = hoaDon.maPhieu;
                sheet.Cells[$"C{row}"].Value = hoaDon.ngayDen.ToString("dd/MM/yyyy");
                sheet.Cells[$"D{row}"].Value = hoaDon.ngayDi.ToString("dd/MM/yyyy");
                sheet.Cells[$"E{row}"].Value = hoaDon.tienPhong;
                sheet.Cells[$"F{row}"].Value = hoaDon.tienDichVu;
                sheet.Cells[$"G{row}"].Value = hoaDon.tongTien;
                row++;
            });

            sheet.Row(row).Style.Font.Bold = true;
            sheet.Cells[$"A{row}:D{row}"].Merge = true;
            sheet.Cells[$"A{row}"].Value = "Tổng cộng";
            sheet.Cells[$"E{row}"].Formula = $"SUM(E{3}:E{row - 1})";
            sheet.Cells[$"F{row}"].Formula = $"SUM(F{3}:F{row - 1})";
            sheet.Cells[$"G{row}"].Formula = $"SUM(G{3}:G{row - 1})";


            var range = sheet.Cells[$"A1:G{row}"];
            range.Style.Border.Top.Style = ExcelBorderStyle.Thin;
            range.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
            range.Style.Border.Left.Style = ExcelBorderStyle.Thin;
            range.Style.Border.Right.Style = ExcelBorderStyle.Thin;

            sheet.Cells[$"A1:G{row}"].AutoFitColumns();

            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "Report.xlsx");
            Response.BinaryWrite(ep.GetAsByteArray());
            Response.End();
        }

        public ActionResult HoaDon(string id)
        {
            var phieuThue = db.PHIEU_THUEPHONG.Find(id);
            return View(phieuThue);
        }

        private DoanhThuModel CalDoanhThuNgay(string date)
        {
            DoanhThuModel doanhThu = new DoanhThuModel();

            // Tính doanh thu của từng phòng
            // Khởi tạo doanh thu = 0 cho từng phòng
            var phongs = db.PHONGs.ToList();
            List<DoanhThuPhongModel> doanhThuPhongs = new List<DoanhThuPhongModel>();
            phongs.ForEach(phong =>
            {
                DoanhThuPhongModel doanhThuPhong = new DoanhThuPhongModel();
                doanhThuPhong.maPhong = phong.MA_PHONG;
                doanhThuPhong.doanhThu = 0;
                doanhThuPhongs.Add(doanhThuPhong);
            });

            // chuyển ngày cần tính daonh thu sang DateTime
            DateTime dateNeed = DateTime.ParseExact(date, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture);

            // Lọc các phiếu thêu phòng thỏa ngày cần tính doanh thu
            // -> cộng doanh thu cho phòng tương ứng khi được thuê (có trong bảng CT thuê phòng)
            var phieuThuePhongs = db.PHIEU_THUEPHONG.ToList();
            phieuThuePhongs
                .Where(phieu => {
                    return DateTime.Compare(phieu.NGAYDEN, dateNeed) <= 0 && DateTime.Compare(phieu.NGAYDI, dateNeed) >= 0;
                })
                .ToList()
                .ForEach(phieu => {
                    var ctPhieu = phieu.CHITIET_THUEPHONG.ToList();
                    ctPhieu.ForEach(ct =>
                    {
                        doanhThuPhongs.Find(dt => dt.maPhong == ct.MAPHONG).doanhThu += (decimal)ct.GIAPHONG;
                    });
                });
            doanhThu.doanhThuPhongs = doanhThuPhongs;

            // Tính doanh thu thuê dịch vụ
            decimal doanhThuDichVu = 0;
            phieuThuePhongs
                .Where(phieu => DateTime.Compare(phieu.NGAYDI, dateNeed) == 0)
                .ToList()
                .ForEach(phieu => {
                    var ctPhieu = phieu.CHITIET_THUEDICHVU.ToList();
                    ctPhieu.ForEach(ct =>
                    {
                        doanhThuDichVu += (decimal)ct.GIA_DICHVU * ct.SOLUONG;
                    });
                });
            doanhThu.doanhThuDichVu = doanhThuDichVu;
            
            return doanhThu;
        }

        public ActionResult DoanhThuNgay(string date)
        {
            if (date == null)
            {
                ViewBag.username = ((LoginSessionModel)Session["session"]).name;
                return View(new DoanhThuModel());
            }

            DoanhThuModel doanhThu = CalDoanhThuNgay(date);

            ViewBag.date = date;
            ViewBag.username = ((LoginSessionModel)Session["session"]).name;
            return View(doanhThu);
        }

        private DoanhThuModel CalDoanhThuThang(string monthAndYear)
        {
            string[] my = monthAndYear.Split(new[] { '-' });
            DoanhThuModel doanhThu = new DoanhThuModel();
            int yearNeed = Int32.Parse(my[0]);
            int monthNeed = Int32.Parse(my[1]);

            DateTime dateMin = new DateTime(yearNeed, monthNeed, 1);
            DateTime dateMax = new DateTime(yearNeed, monthNeed + 1, 1);
            dateMax = dateMax.AddDays(-1);

            // Tính doanh thu của từng phòng
            // Khởi tạo doanh thu = 0 cho từng phòng
            var phongs = db.PHONGs.ToList();
            List<DoanhThuPhongModel> doanhThuPhongs = new List<DoanhThuPhongModel>();
            phongs.ForEach(phong =>
            {
                DoanhThuPhongModel doanhThuPhong = new DoanhThuPhongModel();
                doanhThuPhong.maPhong = phong.MA_PHONG;
                doanhThuPhong.doanhThu = 0;
                doanhThuPhongs.Add(doanhThuPhong);
            });

            // Lọc các phiếu thêu phòng thỏa ngày cần tính doanh thu

            var phieuThuePhongs = db.PHIEU_THUEPHONG.ToList();


            // cộng doanh thu cho phòng tương ứng khi được thuê (có trong bảng CT thuê phòng)
            phieuThuePhongs
                .Where(phieu => {
                    return DateTime.Compare(phieu.NGAYDEN, dateMax) <= 0 && DateTime.Compare(phieu.NGAYDI, dateMin) >= 0;
                })

QLKS_H2O/Areas/Admin/Views/KeToan/DoanhThuNam.cshtml
@model QLKS_H2O.Areas.Admin.Models.DoanhThuModel

@{
    ViewBag.Title = "Kế toán: Doanh thu";
    Layout = "~/Areas/Admin/Views/Shared/_KeToanLayout.cshtml";
    ViewBag.tag = "dtnam";
}

<h4 class="text-center my-2">DOANH THU NĂM</h4>

@using (Html.BeginForm("DoanhThuNam", "KeToan", FormMethod.Get))
{
    <div class="w-25 mx-auto d-flex align-items-center">
        <label for="year" class="mx-2">Năm</label>
        <input type="number" class="form-control" id="year" name="year" min="2010" value="@ViewBag.year">
        <button type="submit" class="btn btn-success ml-2">Tính</button>
    </div>
}

@if (Model.doanhThuPhongs.Count() > 0)
{
    <table class="table table-sm text-center table-bordered table-striped w-50 mx-auto mt-2">
        <thead class="thead-dark">
            <tr>
                <th>STT</th>
                <th>Phòng</th>
                <th>Tổng tiền phòng</th>
            </tr>
        </thead>
        <tbody id="tableBody">
            @{
                int index = 0;
                decimal tongDoanhThuPhong = 0;
            }
            @foreach (var phong in Model.doanhThuPhongs)
            {
                <tr>
                    <td>
                        @{index++;}
                        @index
                    </td>
                    <td>@phong.maPhong</td>
                    <td>@phong.doanhThu.ToString("#,##0.0")</td>
                    @{ tongDoanhThuPhong += phong.doanhThu;}
                </tr>
            }
            <tr>
                <th colspan="2">Tổng doanh thu tiền thuê phòng</th>
                <td>@tongDoanhThuPhong.ToString("#,##0.0")</td>
            </tr>
            <tr>
                <th colspan="2">Tổng doanh thu tiền thuê dịch vụ</th>
                <td>@Model.doanhThuDichVu.ToString("#,##0.0")</td>
            </tr>
            <tr>
                <th colspan="2">Tổng doanh thu</th>
                <td>
                    @{var tong = Model.doanhThuDichVu + tongDoanhThuPhong;}
                    @tong.ToString("#,##0.0")
                </td>
            </tr>
        </tbody>
    </table>
    <div class="text-right w-50 mx-auto">
        @Html.ActionLink("Download", "DoanhThuNamDownload", "KeToan", new { year = ViewBag.year }, new { @class = "btn btn-success btn-sm" })
    </div>
}

<a href="@Request.UrlReferrer">Quay lại</a>

QLKS_H2O/Areas/Admin/Views/KeToan/DoanhThuNgay.cshtml
@model QLKS_H2O.Areas.Admin.Models.DoanhThuModel

@{
    ViewBag.Title = "Kế toán: Doanh thu";
    Layout = "~/Areas/Admin/Views/Shared/_KeToanLayout.cshtml";
    ViewBag.tag = "dtngay";
}

<h4 class="text-center my-2">DOANH THU NGÀY</h4>

@using (Html.BeginForm("DoanhThuNgay", "KeToan", FormMethod.Get))
{
    <div class="form-group w-50 mx-auto d-flex align-items-center">
        <label for="date" class="col-4">Ngày tính doanh thu</label>
        <input type="date" class="form-control" id="date" name="date" value="@ViewBag.date" />
        <button type="submit" class="btn btn-success ml-2">Tính</button>
    </div>
}

@if (Model.doanhThuPhongs.Count() > 0)
{
    <table class="table table-sm text-center table-bordered table-striped w-50 mx-auto">
        <thead class="thead-dark">
            <tr>
                <th>STT</th>
                <th>Phòng</th>
                <th>Tổng tiền phòng</th>
            </tr>
        </thead>
        <tbody id="tableBody">
            @{
                int index = 0;
                decimal tongDoanhThuPhong = 0;
            }
            @foreach (var phong in Model.doanhThuPhongs)
            {
                <tr>
                    <td>
                        @{index++;}
                        @index
                    </td>
                    <td>@phong.maPhong</td>
                    <td>@phong.doanhThu.ToString("#,##0.0")</td>
                    @{ tongDoanhThuPhong += phong.doanhThu;}
                </tr>
            }
            <tr>
                <th colspan="2">Tổng doanh thu tiền thuê phòng</th>
                <td>@tongDoanhThuPhong.ToString("#,##0.0")</td>
            </tr>
            <tr>
                <th colspan="2">Tổng doanh thu tiền thuê dịch vụ</th>
                <td>@Model.doanhThuDichVu.ToString("#,##0.0")</td>
            </tr>
            <tr>
                <th colspan="2">Tổng doanh thu</th>
                <td>
                    @{var tong = Model.doanhThuDichVu + tongDoanhThuPhong;}
                    @tong.ToString("#,##0.0")
                </td>
            </tr>
        </tbody>
    </table>
    <div class="text-right w-50 mx-auto">
        @Html.ActionLink("Download", "DoanhThuNgayDownload", "KeToan", new { date = ViewBag.date }, new { @class = "btn btn-success btn-sm" })
    </div>
}

<a href="@Request.UrlReferrer">Quay lại</a>

QLKS_H2O/Areas/Admin/Views/KeToan/DoanhThuThang.cshtml
@model QLKS_H2O.Areas.Admin.Models.DoanhThuModel

@{
    ViewBag.Title = "Kế toán: Doanh thu";
    Layout = "~/Areas/Admin/Views/Shared/_KeToanLayout.cshtml";
    ViewBag.tag = "dtthang";
}

<h4 class="text-center my-2">DOANH THU THÁNG</h4>

@using (Html.BeginForm("DoanhThuThang", "KeToan", FormMethod.Get))
{
    <div class="w-25 mx-auto d-flex align-items-center">
        <label for="month" class="mr-2">Tháng</label>
        <input type="month" class="form-control" id="month" name="monthAndYear" value="@ViewBag.monthandyear">
        <button type="submit" class="btn btn-success ml-2">Tính</button>
    </div>
}

@if (Model.doanhThuPhongs.Count() > 0)
{
    <table class="table table-sm text-center table-bordered table-striped w-50 mx-auto mt-2">
        <thead class="thead-dark">
            <tr>
                <th>STT</th>
                <th>Phòng</th>
                <th>Tổng tiền phòng</th>
            </tr>
        </thead>
        <tbody id="tableBody">
            @{
                int index = 0;
                decimal tongDoanhThuPhong = 0;
            }
            @foreach (var phong in Model.doanhThuPhongs)
            {
                <tr>
                    <td>
                        @{index++;}
                        @index
                    </td>
                    <td>@phong.maPhong</td>
                    <td>@phong.doanhThu.ToString("#,##0.0")</td>
                    @{ tongDoanhThuPhong += phong.doanhThu;}
                </tr>
            }
            <tr>
                <th colspan="2">Tổng doanh thu tiền thuê phòng</th>
                <td>@tongDoanhThuPhong.ToString("#,##0.0")</td>
            </tr>
            <tr>
                <th colspan="2">Tổng doanh thu tiền thuê dịch vụ</th>
                <td>@Model.doanhThuDichVu.ToString("#,##0.0")</td>
            </tr>
            <tr>
                <th colspan="2">Tổng doanh thu</th>
                <td>
                    @{var tong = Model.doanhThuDichVu + tongDoanhThuPhong;}
                    @tong.ToString("#,##0.0")
                </td>
            </tr>
        </tbody>
    </table>
    <div class="text-right w-50 mx-auto">
        @Html.ActionLink("Download", "DoanhThuThangDownload", "KeToan", new { monthAndYear = ViewBag.monthandyear }, new { @class = "btn btn-success btn-sm" })
    </div>
}

<a href="@Request.UrlReferrer">Quay lại</a>

QLKS_H2O/Areas/Admin/Views/KeToan/HoaDon.cshtml
@model QLKS_H2O.Models.PHIEU_THUEPHONG
@{
    ViewBag.Title = "Kế toán: Hóa đơn";
    Layout = "~/Areas/Admin/Views/Shared/_KeToanLayout.cshtml";
    ViewBag.tag = "hoadon";
    int indexPhong = 0;
    int indexDichVu = 0;
    decimal tienPhong = 0;
    decimal tienDichVu = 0;
    decimal tienTra = 0;
    double soNgay = (Model.NGAYDI - Model.NGAYDEN).Ticks / 864e9;
}

<div class="mx-auto p-3" style="border: 1px solid black; border-radius: 5px; box-shadow: 5px 5px 10px #808080; width: 760px;">
    <h3 class="text-center mt-4">HÓA ĐƠN THANH TOÁN</h3>
    <div class="p-4">
        <table class="table table-sm table-borderless">
            <tr>
                <th>Họ và tên khách hàng</th>
                <td>@Model.KHACH.HOTEN_KHACH</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th>CMND/PASSPORT</th>
                <td>@Model.KHACH.CMND</td>
                <th>Quốc tịch</th>
                <td>@Model.KHACH.QUOCTICH</td>
            </tr>
            <tr>
                <th>Điện thoại</th>
                <td>@Model.KHACH.DIENTHOAI</td>
                <td></td>
                <td></td>
            </tr>
        </table>

        <b>Chi tiết sử dụng phòng</b>
        <table class="table table-sm text-center table-bordered">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Phòng</th>
                    <th>Loại phòng</th>
                    <th>Số ngày</th>
                    <th>Đơn giá (một đêm)</th>
                    <th>Thành tiền</th>
                </tr>
            </thead>
            <tbody id="phongBody">
                @foreach (var ctThuePhong in Model.CHITIET_THUEPHONG)
                {
                    <tr>
                        <td>
                            @{indexPhong++;}
                            @indexPhong
                        </td>
                        <td>@ctThuePhong.MAPHONG</td>
                        <td>@ctThuePhong.PHONG.LOAIPHONG.TEN_LOAIPHONG</td>
                        <td>@soNgay</td>
                        <td>@(String.Format("{0,1:N1}", ctThuePhong.GIAPHONG))đ</td>
                        <td>@(String.Format("{0,1:N1}", ctThuePhong.GIAPHONG * (decimal)soNgay))đ</td>
                        @{ tienPhong += (decimal)ctThuePhong.GIAPHONG* (decimal)soNgay;}

                    </tr>
                            }
                <tr>
                    <td colspan="5">
                        <b>Tổng cộng</b>
                    </td>
                    <td>@(String.Format("{0,1:N1}", tienPhong))đ</td>
                </tr>
            </tbody>
        </table>

        <b>Chi tiết sử dụng dịch vụ</b>
        <table class="table table-sm text-center table-bordered">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Dịch vụ</th>
                    <th>Số lượng</th>
                    <th>Đơn giá</th>
                    <th>Thành tiền</th>
                </tr>
            </thead>
            <tbody id="dichVuBody">
                @foreach (var ctThueDV in Model.CHITIET_THUEDICHVU)
                {
                    <tr>
                        <td>
                            @{indexDichVu++;}
                            @indexDichVu
                        </td>
                        <td>@ctThueDV.DICHVU.TEN_DICHVU</td>
                        <td>@ctThueDV.SOLUONG</td>
                        <td>@(String.Format("{0,1:N1}", ctThueDV.GIA_DICHVU))đ</td>
                        <td>@(String.Format("{0,1:N1}", ctThueDV.GIA_DICHVU * ctThueDV.SOLUONG))đ</td>
                        @{ tienDichVu += (decimal)ctThueDV.GIA_DICHVU * ctThueDV.SOLUONG;}
                    </tr>
                }
                <tr>
                    <td colspan="4">
                        <b>Tổng cộng</b>
                    </td>
                    <td>@(String.Format("{0,1:N1}", tienDichVu))đ</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <tr>
                <th>Tổng tiền</th>
                <td id="tien" class="text-right">@(String.Format("{0,1:N1}", tienPhong + tienDichVu))đ</td>
            </tr>
        </table>
        
        <div class="text-right pr-5 mb-3">
            <i>Ngày @(Model.NGAYDI.Day) tháng @(Model.NGAYDI.Month) năm @(Model.NGAYDI.Year)</i>
        </div>
    </div>
</div>

<a href="@Request.UrlReferrer">Quay lại</a>

QLKS_H2O/Areas/Admin/Views/KeToan/Index.cshtml
@model List<QLKS_H2O.Areas.Admin.Models.HoaDonModel>

@{
    ViewBag.Title = "Kế toán: Hóa đơn";
    Layout = "~/Areas/Admin/Views/Shared/_KeToanLayout.cshtml";
    ViewBag.tag = "hoadon";
    //int index = 0;
    var grid = new WebGrid(source: Model, canPage: true, defaultSort: "ngayDi", rowsPerPage: 5);
}

<h4 class="text-center my-2">DANH SÁCH HÓA ĐƠN</h4>

@using (Html.BeginForm("Index", "KeToan", FormMethod.Get)) {
<table class="w-50 mx-auto my-2">
    <tr>
        <th>
            <label for="billid">Mã phiếu</label>
        </th>
        <th>
            <input type="text" name="billid" id="billid" value="@ViewBag.billid" class="form-control form-control-sm" />
        </th>
    </tr>
    <tr>
        <th>
            <label for="datecreate">Ngày lập hóa đơn</label>
        </th>
        <th>
            <input type="date" name="datecreate" id="datecreate" value="@ViewBag.datecreate" class="form-control form-control-sm" />
        </th>
    </tr>
    <tr>
        <th>Tổng tiền</th>
        <td>
            <label for="summin" class="d-inline">Từ</label>
            <input type="number" name="summin" id="summin" value="@ViewBag.summin" class="form-control form-control-sm d-inline" />
        </td>
        <td>
            <label for="summax" class="d-inline">Đến</label>
            <input type="number" name="summax" id="summax" value="@ViewBag.summax" class="form-control form-control-sm d-inline" />
        </td>
    </tr>
    <tr>
        <td colspan="3" class="text-right">
            <button type="button" class="btn btn-secondary btn-sm" id="btnreset">Nhập lại</button>
            <button type="submit" class="btn btn-success btn-sm">Tìm kiếm</button>
        </td>
    </tr>
</table>
}

<div id="grid-main">
    @grid.GetHtml(
     tableStyle: "table table-sm text-center table-bordered table-striped",
     headerStyle: "thead-dark",
     footerStyle: "grid-footer",
     fillEmptyRows: false,
     mode: WebGridPagerModes.Numeric,
     columns: new[]
      {
            grid.Column("STT",format: item => 
                item.WebGrid.Rows.IndexOf(item) + 1 
                + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage)
                * grid.RowsPerPage * grid.PageIndex),
            grid.Column("maPhieu", "Mã phiếu"),
            grid.Column("ngayDen", "Ngày đến", item => item.ngayDen.ToString("dd/MM/yyyy")),
            grid.Column("ngayDi", "Ngày đi", item => item.ngayDi.ToString("dd/MM/yyyy")),
            grid.Column("tienPhong", "Tổng tiền phòng", item => item.tienPhong.ToString("#,##0.0")),
            grid.Column("tienDichVu", "Tổng tiền dịch vụ", item => item.tienDichVu.ToString("#,##0.0")),
            grid.Column("tongTien", "Tổng tiền", item => item.tongTien.ToString("#,##0.0")),
            grid.Column(format: item => Html.ActionLink("Chi tiết", "HoaDon", "KeToan", new { id = item.maPhieu}, null))
      }
    )
</div>

<div class="text-right">
    @Html.ActionLink("Download", "DownloadHoaDon", "KeToan", 
        new { billid = ViewBag.billid, datecreate = ViewBag.datecreate, summin = ViewBag.summin, summax = ViewBag.summax }, 
        new { @class = "btn btn-success btn-sm" }
    )
</div>

<script>
    document.getElementById('btnreset').addEventListener('click', () => {
        document.getElementById('billid').value = '';
        document.getElementById('datecreate').value = '';
        document.getElementById('summin').value = 0;
        document.getElementById('summax').value = '';
    });
</script>